# Site settings
title: Alessandro Anatrini
description: Computational Artist & Multimedia Educator
url: "https://anatrini.com"
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  works:
    output: true
    permalink: /work/:title/
  pages:
    output: true
    permalink: /:title/
  news:
    output: false
    sort_by: date

# Defaults
defaults:
  - scope:
      path: ""
      type: "works"
    values:
      layout: "work"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

# Sass
sass:
  style: compressed
  sass_dir: _sass
